#!/bin/bash

echo "prefix=$ATLAS_HOME">Makefile.adlcc
touch $1
if test "$#" -eq 0
then
  echo 'Usage: adlcc filename'
  exit 1
fi
#
# See if the filename exists:

if [ ! -f "$1" ] 
then
    echo "Cannot find $1"
    exit 1
else # We found $1.
    BASE_NAME=`echo $1 | cut -d. -f 1`
    FULL_NAME=$1
fi

    if [ "$WINDIR" = "" ]
    then 
	extralib="-ldl"
    else 
        extralib=""
    fi

#
echo "AXLDIR=\$(prefix)" >> Makefile.adlcc
echo "LIBDIR=\$(AXLDIR)/lib/">>Makefile.adlcc
echo "BERKELEY_INC=\${prefix}/include" >> Makefile.adlcc
echo "BERKELEY_LIB=\${prefix}/lib/libdb.a" >> Makefile.adlcc
echo "ADL_INC=\${AXLDIR}/include" >> Makefile.adlcc
echo "ADL_LIB=\$(LIBDIR)/libatlas.a" >> Makefile.adlcc
echo "IMDB_LIB=\$(LIBDIR)/libimdb.a" >> Makefile.adlcc
echo "RTREE_LIB=\$(LIBDIR)/librtree.a" >> Makefile.adlcc
echo "SWIMFIS_LIB=\$(LIBDIR)/libswimfis.a" >> Makefile.adlcc
#############################

echo "CXX=g++" >> Makefile.adlcc
#
#
echo "${BASE_NAME}: ${BASE_NAME}.o" >> Makefile.adlcc
    echo "	\${CXX} -g -w -o ${BASE_NAME} ${BASE_NAME}.o \$(prefix)/lib/libatlas.a \$(prefix)/lib/libdbug.a \${ADL_LIB} \${SWIMFIS_LIB} \${BERKELEY_LIB} \${IMDB_LIB} \${RTREE_LIB} /usr/lib/libmm.a $extralib" >> Makefile.adlcc

echo "">> Makefile.adlcc

echo "${BASE_NAME}.o: $1" >> Makefile.adlcc
echo "	\${CXX} -g -w -c -I\${BERKELEY_INC} -I\${ADL_INC} ${FULL_NAME} " >> Makefile.adlcc


make -f Makefile.adlcc

exit 0



