#!/bin/sh

export LD_LIBRARY_PATH=./lib
(cd ./lib; make) 

RunTest() {
    i="$1"
    BASENAME=`echo $i | cut -d. -f 1`
    echo testing $BASENAME ...

    if [ ! -f $BASENAME.result ]; then
        echo "skipped. Can't locate $BASENAME.result"
    else
	
	adlc -f adlctmp.cc $BASENAME.adl
	adlcc adlctmp.cc

	./adlctmp > adltestsuittmp

	dos2unix adltestsuittmp 2>null

        cmp=`diff -b adltestsuittmp $BASENAME.result`

        if [ "$cmp" = "" ]; then
            echo "TEST $i : PASS"
        else
	    sort adltestsuittmp > sort.1
	    sort $BASENAME.result > sort.2
	    cmp= `diff sort.1 sort.2`
	    if [ "$cmp" = "" ]; then
		echo "TEST $BASENAME **ORDER**"
	    else 
	echo "*********CURRENT RESULT***************"
	cat adltestsuittmp
	echo "*********ORIGINAL RESULT**************"
	cat $BASENAME.result
	echo "**************************************"


		echo "TEST $BASENAME FAILED"
	    fi
        fi

	rm -rf adlctmp adlctmp.*
    fi
}

if [ $# -ne 0 ]
then
  for arg in "$@"
  do
    RunTest $arg
  done            
else
  for i in `ls src/$1*.adl`; do
    RunTest $i
  done
fi
