/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class iterate */

#ifndef _Included_iterate
#define _Included_iterate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     iterate
 * Method:    hadoopiterate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_iterate_hadoopiterate
  (JNIEnv *, jclass, jint);

/*
 * Class:     iterate
 * Method:    hadoopterminate
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_iterate_hadoopterminate
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
