/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SumUda */

#ifndef _Included_SumUda
#define _Included_SumUda
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SumUda
 * Method:    myiterate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_SumUda_myiterate
  (JNIEnv *, jclass, jint);

/*
 * Class:     SumUda
 * Method:    terminate
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_SumUda_terminate
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
