#ifndef NT_ERR_H
#define NT_ERR_H

#include <errno.h>
//extern int errno;

extern bool EM_anyErrors;


/************************************************************
                ERROR MESSAGE
************************************************************/
typedef enum {
  ERR_NONE=0,
  /* The following err types are SORTED by their names. When you add a
     new err type here, please also add it in err.cc. */
  ERR_AGGREGATE_BUILTIN_TYPE,
  ERR_AGGREGATE_CASCADING,
  ERR_AGGREGATE_GROUPBY,
  ERR_BERKELEY_DB,
  ERR_BUFFER,
  ERR_COMPLEX_DATA,
  ERR_COMPLEX_FUNC_EXPECTED,
  ERR_CREATE_EXIST_FUNCTION,
  ERR_CREATE_EXIST_TABLE,
  ERR_CREATE_STREAM,
  ERR_CREATE_VIEW,
  ERR_DATATYPE,
  ERR_DBT_INCOMPATIBLE,
  ERR_DIV_ZERO,
  ERR_DUPLICATE_FIELD_NAME,
  ERR_DUPLICATE_JOIN_NAME,
  ERR_FUNCTION_NOT_EXIST,
  ERR_GROUPBY,
  ERR_HISTORY,
  ERR_IDENT_UNDEFINED,
  ERR_ID_UNDEFINED,
  ERR_INCOMPATIBLE_TYPE,
  ERR_INCOMPATIBLE_STREAMS,
  ERR_INCOMPATIBLE_TIMEKEY,
  ERR_INMEM_TABLE,
  ERR_INVALID_ARG,
  ERR_INVALID_COMMAND,
  ERR_INVALID_DELETE_FUNC_USE,
  ERR_INVALID_EXTERNAL_NAME,
  ERR_INVALID_INDEX_SPEC,
  ERR_INVALID_OLDEST_USE,
  ERR_INVALID_PARAM_TABLE,
  ERR_INVALID_PARTITION_USE,
  ERR_INVALID_PORT_NUM,
  ERR_INVALID_SCOPE,
  ERR_INVALID_STMT_IN_FLOW,
  ERR_INVALID_TABLE_FUNCTION_USE,
  ERR_IO,
  ERR_JOIN_STREAM_TABLE,
  ERR_KEY_EXISTS,
  ERR_KEY_NOT_FOUND,
  ERR_KEY_REF_MATCH,
  ERR_NTSQL_INTERNAL,
  ERR_NON_BUILTIN_FUNC,
  ERR_NON_REFERENCE_TYPE,
  ERR_NON_SCALAR,
  ERR_OID_ARITHMETIC,
  ERR_OID_INSERTION,
  ERR_OID_NONEXIST,
  ERR_OPEN_FILE,
  ERR_OUT_OF_MEMORY,
  ERR_PANIC,
  ERR_REDECLARATION,
  ERR_REF_MEMORY_ONLY,
  ERR_REF_TYPE_MISMATCH,
  ERR_RTREE_DIMENSION,
  ERR_RTREE_MEMORY,
  ERR_RTREE_KEYTYPE,
  ERR_SQRT_NEGATIVE,
  ERR_STREAM,
  ERR_STREAM_TARGET_SPEC,
  ERR_SUBQUERY,
  ERR_SYNTAX,
  ERR_TABLE_NOT_EXIST,
  ERR_TARGET_STREAM_USE,
  ERR_TIMESTAMP,
  ERR_TO_BE_IMPLEMENTED,
  ERR_TUPLE_TYPE_REQUIRED,
  ERR_UNDEFINED_FIELD,
  ERR_UNDEFINED_FUNCTION,
  ERR_UNDEFINED_REF,
  ERR_UNDEFINED_TYPE,
  ERR_UNDEFINED_VARIABLE,
  ERR_UNEXPECTED,
  ERR_UNMATCH_CARDINALITY,
  ERR_UNMATCH_INIT_TYPE,
  ERR_UNMATCH_UNION_TYPE,
  ERR_UNSUPPORTED_CASE_TYPE,
  ERR_WINDOW_NOT_ALLOWED_ON_TABLE,
  ERR_WINDOW_UDA_REQUIRED,
  ERR_WINDOW_USE_INVALID,
  ERR_WRONG_NUMBER_OF_ARGS,
} err_t;

void EM_newline(void);

extern int EM_tokPos;
void EM_error(err_t, int, char *, ...);
void EM_error(int, err_t, int, char *, ...);
void EM_impossible(char *,...);
void EM_reset(char *filename);

#endif







