#!/bin/sh
INCLUDES="-I../../../ -I../../../dbug -I../../ -I../"
esl_LDADD="/usr/lib/libmm.a ../../libatlas.a ../../../dbug/libdbug.a -ldl"
export LD_LIBRARY_PATH=../

RunTest() {
    BASENAME=`echo $i | cut -d. -f 1`
    echo testing $BASENAME ...

    if [ ! -f $BASENAME.result ]; then
        echo "skipped. Can't locate $BASENAME.result"
    else
	
	# TODO(nlaptev): Remove the commend symbol below so that the output is forwarded to the appropriate file.
	$BASENAME # > adltestsuittmp

	dos2unix adltestsuittmp 2>null

        cmp=`diff -b adltestsuittmp $BASENAME.result`

        if [ "$cmp" = "" ]; then
            echo "TEST $i : PASS"
        else
		    echo "TEST $BASENAME FAILED"
	    fi
	rm -rf adlctmp adlctmp.*
    fi
}

if [ $# -ne 0 ]
then
  for arg in "$@"
  do
    RunTest $arg
  done            
else
  for i in `ls src/port5551_test`; do
    RunTest $i
  done
fi
